// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTPa0u6OsDD2FjbRu_XYkayV95Lby884',
    appId: '1:1074101022704:android:8ff67d98d6ea3c227a3735',
    messagingSenderId: '1074101022704',
    projectId: 'hot-project-56080',
    databaseURL:
        'https://hot-project-56080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hot-project-56080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqY4J0mkybyLwscyPhUiH3CVsvgQMOcpc',
    appId: '1:1074101022704:ios:18798c7798e6e30c7a3735',
    messagingSenderId: '1074101022704',
    projectId: 'hot-project-56080',
    databaseURL:
        'https://hot-project-56080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hot-project-56080.appspot.com',
    iosBundleId: 'com.example.heartplanner',
  );
}
